### ISSUE TITLE
emmet syntax

### ISSUE THREAD

**Issue by mbarzda** [tonyspiro/shorti#1]
useful lib, but emmet syntax would look much better: http://docs.emmet.io/cheat-sheet/ . An ex. negative shorti should be l-5 instead l-5n (left: -5px;) :)

**Comment by tonyspiro** [comment]
Thanks for the suggestion.  Right now Shorti processes the value by splitting the '-'.  This is easier syntax programmatically and, in my opinion, is easier to read (l5 could be mistaken for 15).  FYI, you could also use l-n5 if it makes more sense for you.
